name = "Crows Zeus Additions"
author = "Crowdedlight"
prefix = "crowsza"
mainprefix = "z"

sig_version = 3
reuse_private_key = true

[files]
include = [
  "mod.cpp",
  "crow_icon.paa",
  "logo_crow.paa",
  "LICENSE",
  "README.md",
  "./include",
]
exclude = [
  "*.psd",
  "*.png",
  "*.tga"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"
  
releasebuild = [
  "@zip @crowsza_{{version}}"
]
  
[properties]
author = "Crowdedlight"
url = "https://github.com/Crowdedlight/Crows-Zeus-Additions"